import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../data/models/transaction.dart';
import '../core/constants/app_constants.dart';

/// Generates professional PDF reports for expense data.
class PdfExportService {
  static final NumberFormat _currencyFormat = NumberFormat('#,##,##0', 'en_IN');
  static final DateFormat _dateFormat = DateFormat('dd MMM yyyy');

  /// Generate a PDF report for the given transactions within a date range.
  static Future<Uint8List> generateReport({
    required List<TransactionModel> transactions,
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    final pdf = pw.Document();

    final totalDebits = transactions
        .where((t) => t.isDebit)
        .fold(0.0, (sum, t) => sum + t.amount);
    final totalCredits = transactions
        .where((t) => t.isCredit)
        .fold(0.0, (sum, t) => sum + t.amount);
    final netBalance = totalCredits - totalDebits;

    // Find most used category
    final catMap = <String, double>{};
    for (final t in transactions.where((t) => t.isDebit)) {
      catMap[t.category] = (catMap[t.category] ?? 0) + t.amount;
    }
    final mostUsedCategory = catMap.entries.isEmpty
        ? 'N/A'
        : catMap.entries.reduce((a, b) => a.value > b.value ? a : b).key;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(context, startDate, endDate),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          // Summary Section
          _buildSummarySection(
            totalDebits: totalDebits,
            totalCredits: totalCredits,
            netBalance: netBalance,
            transactionCount: transactions.length,
            mostUsedCategory: mostUsedCategory,
          ),
          pw.SizedBox(height: 20),

          // Transaction Table
          _buildTransactionTable(transactions),
          pw.SizedBox(height: 20),

          // Category Breakdown
          _buildCategoryBreakdown(transactions),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(
    pw.Context context,
    DateTime start,
    DateTime end,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  AppConstants.appName,
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromInt(0xFF6C3AED),
                  ),
                ),
                pw.Text(
                  'Personal Expense Report',
                  style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
                ),
              ],
            ),
            pw.Text(
              '${_dateFormat.format(start)} - ${_dateFormat.format(end)}',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Divider(color: PdfColor.fromInt(0xFF6C3AED)),
        pw.SizedBox(height: 8),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Column(
      children: [
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 4),
        pw.Text(
          'Generated by ${AppConstants.appName} on ${_dateFormat.format(DateTime.now())}',
          style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
        ),
      ],
    );
  }

  static pw.Widget _buildSummarySection({
    required double totalDebits,
    required double totalCredits,
    required double netBalance,
    required int transactionCount,
    required String mostUsedCategory,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Summary',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey800,
          ),
        ),
        pw.SizedBox(height: 10),
        pw.Row(
          children: [
            _summaryCard(
              'Total Expenses',
              '₹${_currencyFormat.format(totalDebits)}',
              PdfColor.fromInt(0xFFEF4444),
            ),
            pw.SizedBox(width: 12),
            _summaryCard(
              'Total Income',
              '₹${_currencyFormat.format(totalCredits)}',
              PdfColor.fromInt(0xFF10B981),
            ),
            pw.SizedBox(width: 12),
            _summaryCard(
              'Net Balance',
              '₹${_currencyFormat.format(netBalance.abs())}',
              netBalance >= 0
                  ? PdfColor.fromInt(0xFF10B981)
                  : PdfColor.fromInt(0xFFEF4444),
            ),
            pw.SizedBox(width: 12),
            _summaryCard(
              'Transactions',
              '$transactionCount',
              PdfColor.fromInt(0xFF6C3AED),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColor.fromInt(0xFFF3F0FF),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
          ),
          child: pw.Row(
            children: [
              pw.Text(
                'Most Used Category: ',
                style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
              ),
              pw.Text(
                mostUsedCategory,
                style: pw.TextStyle(
                  fontSize: 11,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromInt(0xFF6C3AED),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _summaryCard(String label, String value, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: PdfColor.fromInt(
            ((0.08 * 255).round() << 24) |
                ((color.red * 255).round() << 16) |
                ((color.green * 255).round() << 8) |
                (color.blue * 255).round(),
          ),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
          border: pw.Border.all(
            color: PdfColor.fromInt(
              ((0.2 * 255).round() << 24) |
                  ((color.red * 255).round() << 16) |
                  ((color.green * 255).round() << 8) |
                  (color.blue * 255).round(),
            ),
            width: 0.5,
          ),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              label,
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: color,
              ),
            ),
          ],
        ),
      ),
    );
  }

  static pw.Widget _buildTransactionTable(List<TransactionModel> transactions) {
    final sorted = [...transactions]..sort((a, b) => b.date.compareTo(a.date));

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Transactions (${transactions.length})',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey800,
          ),
        ),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          children: [
            // Header row
            pw.TableRow(
              decoration: pw.BoxDecoration(color: PdfColor.fromInt(0xFF6C3AED)),
              children: [
                _tableHeader('Date'),
                _tableHeader('Amount'),
                _tableHeader('Type'),
                _tableHeader('Category'),
                _tableHeader('Merchant'),
              ],
            ),
            // Data rows
            ...sorted.map(
              (t) => pw.TableRow(
                decoration: pw.BoxDecoration(
                  color: sorted.indexOf(t) % 2 == 0
                      ? PdfColors.white
                      : PdfColors.grey100,
                ),
                children: [
                  _tableCell(_dateFormat.format(t.date)),
                  _tableCell(
                    '₹${_currencyFormat.format(t.amount)}',
                    color: t.isDebit
                        ? PdfColor.fromInt(0xFFEF4444)
                        : PdfColor.fromInt(0xFF10B981),
                  ),
                  _tableCell(t.type),
                  _tableCell(t.category),
                  _tableCell(t.merchant),
                ],
              ),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
        ),
      ),
    );
  }

  static pw.Widget _tableCell(String text, {PdfColor? color}) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 8, color: color ?? PdfColors.grey800),
      ),
    );
  }

  static pw.Widget _buildCategoryBreakdown(
    List<TransactionModel> transactions,
  ) {
    final catMap = <String, double>{};
    for (final t in transactions.where((t) => t.isDebit)) {
      catMap[t.category] = (catMap[t.category] ?? 0) + t.amount;
    }

    final sorted = catMap.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final total = catMap.values.fold(0.0, (a, b) => a + b);

    if (sorted.isEmpty) return pw.SizedBox.shrink();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Category Breakdown',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey800,
          ),
        ),
        pw.SizedBox(height: 10),
        ...sorted.map(
          (entry) => pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 4),
            child: pw.Row(
              children: [
                pw.SizedBox(
                  width: 100,
                  child: pw.Text(
                    entry.key,
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                  ),
                ),
                pw.Expanded(
                  child: pw.Container(
                    height: 14,
                    decoration: pw.BoxDecoration(
                      color: PdfColors.grey200,
                      borderRadius: const pw.BorderRadius.all(
                        pw.Radius.circular(7),
                      ),
                    ),
                    child: pw.Row(
                      children: [
                        pw.Expanded(
                          flex: total > 0
                              ? (entry.value / total * 1000).round().clamp(
                                  0,
                                  1000,
                                )
                              : 0,
                          child: pw.Container(
                            decoration: pw.BoxDecoration(
                              color: PdfColor.fromInt(0xFF6C3AED),
                              borderRadius: const pw.BorderRadius.all(
                                pw.Radius.circular(7),
                              ),
                            ),
                          ),
                        ),
                        pw.Expanded(
                          flex: total > 0
                              ? (1000 - (entry.value / total * 1000).round())
                                    .clamp(0, 1000)
                              : 1000,
                          child: pw.Container(),
                        ),
                      ],
                    ),
                  ),
                ),
                pw.SizedBox(width: 8),
                pw.SizedBox(
                  width: 60,
                  child: pw.Text(
                    '₹${_currencyFormat.format(entry.value)}',
                    style: pw.TextStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.grey800,
                    ),
                  ),
                ),
                pw.SizedBox(
                  width: 35,
                  child: pw.Text(
                    total > 0
                        ? '${(entry.value / total * 100).toStringAsFixed(0)}%'
                        : '0%',
                    style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
                    textAlign: pw.TextAlign.right,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  /// Export transactions to a PDF file and share it.
  static Future<String?> exportAndShare({
    required List<TransactionModel> transactions,
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    if (transactions.isEmpty) return null;

    final pdfBytes = await generateReport(
      transactions: transactions,
      startDate: startDate,
      endDate: endDate,
    );

    final dir = await getTemporaryDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final periodStr =
        '${DateFormat('yyyyMMdd').format(startDate)}-${DateFormat('yyyyMMdd').format(endDate)}';
    final file = File(
      '${dir.path}/pennytracker_report_$periodStr-$timestamp.pdf',
    );
    await file.writeAsBytes(pdfBytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: 'PennyTracker Expense Report',
      text:
          '          Expense report from ${_dateFormat.format(startDate)} to ${_dateFormat.format(endDate)}',
    );

    return file.path;
  }
}
